name: Latest Blog Post Workflow

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update README with blog posts from dev.to
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "BLOG-POST-LIST"
          feed_list: "https://dev.to/feed/niranjanxprt,https://medium.com/feed/@niranjanxprt"
          max_post_count: 5
          template: "- 📝 [$title]($url) - *$date*"
          date_format: "mmm dd, yyyy"
          
      - name: Update README with latest GitHub activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: '🚀 Update README with latest activity'
          MAX_LINES: 5